### ISSUE TITLE
Invalid character error thrown in check interface-metrics on Cisco ASA

### ISSUE THREAD

**Issue by dronehive** [inexio/thola#100]
Hey all! I'm trying to get the interface metrics on my Cisco ASA and it keeps throwing this error:

UNKNOWN: error while adding performance data (error: failed to add performance data point: given performance data point is not valid: metric contains invalid character)

I don't know if it helps, but read interfaces doesn't have the same problem. 

Thanks!

**Comment by TheFireMike** [comment]
Hey!
Could it be the case that an interface of your device has a description which contains the character `'` or `=`?
In the `check interface-metrics` mode, Thola creates a new performance data point for every value of every interface, and adds the respective `ifDescr` of the interface as a label. According to the [Nagios Plugin Development Guidelines](https://nagios-plugins.org/doc/guidelines.html), these labels must not contain the character `'` or `=`.
If one of the interfaces now contains such a character, the monitoring plugin will recognize it and throw the error which you listed.
