### ISSUE TITLE
Warning and critical values should be included in perfdata string

### ISSUE THREAD

**Issue by 0xliam** [inexio/thola#16]
Currently, perfdata strings do not contain the warning and critical value - e.g. on CPU or Memory Usage checks:
```
./thola --ip 1.2.3.4 --snmp-community public check memory-usage --critical 50
CRITICAL: memory usage is 55% | 'memory_usage'=55%;;;;
```

To meet the monitoring plugins development guidelines, perfdata strings should be formatted like below:
```
label=value[uom];[warn];[crit];[min];[max]
```

**Comment by TheFireMike** [comment]
Hey, yeah that's right. We will fix this & release it in the coming days.

**Comment by TheFireMike** [comment]
The fix is online (https://github.com/inexio/thola/commit/dd42e15d078807416a7e0d043a83d586781cf2f1) 🎉
