### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Farom** [inexio/thola#21]
I try to build thola. 
After `git clone https://github.com/inexio/thola.git` and `cd thola` i got an error:

```
> go build
build github.com/inexio/thola: cannot find module for path embed
```

**Comment by TheFireMike** [comment]
Hey,
if you want to build Thola yourself you need the latest version of Go (1.16), because Thola makes use of the new embed feature in Go 1.16. If there are still problems after updating to the latest version of Go, let me know.
Cheers

**Comment by Farom** [comment]
Thanks a lot. I got this error with 1.11.
1.14 is the best i can have in debian buster with stable-backports.
I will try it next year again.

**Comment by Farom** [comment]
For the record: With 1.14 the error is:
```
> go build
config/embedded_files.go:4:2: package embed is not in GOROOT (/usr/lib/go-1.14/src/embed)
core/communicator/device_class.go:19:2: package io/fs is not in GOROOT (/usr/lib/go-1.14/src/io/fs)
```
