### ISSUE TITLE
32bit version of thola - building fails

### ISSUE THREAD

**Issue by kosli** [inexio/thola#23]
It would be great if it would be possible to build a 32 bit version of thola to run it on some older devices. 

Currently the build fails with v0.2.3:
```
env GOARCH=386 /usr/local/go/bin/go build
# github.com/dgraph-io/badger/v2
../../go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/value.go:50:5: constant 4294967295 overflows int
```

**Comment by TheFireMike** [comment]
Hey, yeah unfortunately the [Badger database](https://github.com/dgraph-io/badger) we're using [currently doesn't support 32 bit](https://github.com/dgraph-io/badger/issues/1397#issuecomment-702911092) so our hands are tied here. As soon as badger supports 32 bit builds, there should be no problems with building Thola for 32 bit systems.
