### ISSUE TITLE
Support for HP ProCurve HP J9728A 2920-48G

### ISSUE THREAD

**Issue by studost** [inexio/thola#29]
Hi there,
great work so far. From the docs i can't make out how to integrate for instance an HP J9728A 2920-48G switch model.
I assume that no definition exists for this model, but i'm not sure about that either. When trying to identify the switch i just get:

thola identify IP
Device:
  Class: generic

Where can i define the folder where the YAML files are situated? And if HP Procurves are not supported yet, what ist the best way to add them and to extend thola?

**Comment by TheFireMike** [comment]
Hey,
you're right, for this HP Model there is no device class yet.
The device classes are located in the `config/device-classes` folder in the source code. They will be compiled into the binary, so if you want to add new device classes you need to rebuild Thola after adding them (or if you just want to test them use `go run .`).

For information how the device classes are structured have a look at the [device class part of our documentation](https://docs.thola.io/adding-device/writing-device-classes/) (or get some inspiration by one of the existing device classes ;-) ).

If you need further help building a device class for your device, just let me know. Also feel free to drop us a Pull Request after writing the device class.

**Comment by TheFireMike** [comment]
Please note that you must have Go 1.16 installed if you want to build Thola from source. If that's the case and you need further help, let me know.
