### ISSUE TITLE
Add parameter for non-standard SNMP-port

### ISSUE THREAD

**Issue by ubibits** [inexio/thola#44]
THX for releasing this tool!

We have a tool, that "speaks" SNMP-protocol on a different port to not interfere with standard SNMP-daemon on the same machine. It would be great to query and monitor this tool via thola.

Please add a flag for non-standard SNMP port (<> 161).

**Comment by babos77** [comment]
Hey,

There is already a flag for this: `--snmp-port`.

**Comment by ubibits** [comment]
I'm sorry. I did not recognize this flag, as it is not displayed in the output of `thola -h` nor in the readme.
