### ISSUE TITLE
Support for temperature sensors

### ISSUE THREAD

**Issue by studost** [inexio/thola#48]
I would like to read the reading of **temperature sensors** with Thola. Many devices support specific OIDs for temperature sensors.
Alas the correspondig component ist missing in Thola.

**Comment by mburgholte** [comment]
The idea would be great. Furthermore, it would be cool to be able to read out other things besides temperatures. I manage several industrial switches which also offer redundant connections. These states would also be interesting. Some things would be:

aca - backup config on usb stick in sync with nvram
config - config in sync with nvram
mrp - redundancy available
...

If something like this were available as a kind of module, thola would be superior. For example thole check aca
