### ISSUE TITLE
Levels of loglevel

### ISSUE THREAD

**Issue by mburgholte** [inexio/thola#50]
Hi! i am trying to write my own class. Is it possible to change the loglevel to read the received value? In tshark I see the snmp response, but thola can't do anything with it. Currently I use loglevel=trace

**Comment by babos77** [comment]
Hi! 
Currently trace is the strongest log level. We still need to expand logging for debugging purposes. Can you provide more information on what is not working for you? If you can send an (anonymized) snmprec file of your device including the relevant oids, your device class and info on what is not working i can look into it

**Comment by mburgholte** [comment]
Please excuse my late reply. My intention was in connection with #51. A supposed connection was not established at all. It would have been nice to know what exactly caused this and what was received. Since nothing was received in the end, nothing suitable could be found.
