### ISSUE TITLE
 thola and thola-client are equal in release v0.3.2  in tarball thola_0.3.2_linux_64-bit.tar.gz

### ISSUE THREAD

**Issue by broerman** [inexio/thola#55]
Hello ,
there is a littls bug in the release v0.3.2.

the binarys thola and thola-client are equal in the tarball of linux_64-bit.

**Comment by TheFireMike** [comment]
Hey,
yes we're aware of that, that's a bug in the current goreleaser version. We've already [filled an issue which is already closed,](https://github.com/goreleaser/goreleaser/issues/2300) so this should be fixed as soon as they're releasing a new version, which our GitHub Actions will then use.

**Comment by TheFireMike** [comment]
New goreleaser version is out, I just rereleased v0.3.2 and binaries are looking good.
