### ISSUE TITLE
Error: cannot create any connection to the device

### ISSUE THREAD

**Issue by wh1te0wl** [inexio/thola#62]
Actually Im getting this error of Connection using Thola to identify a device.

[root@vm-centos8 thola]# ./thola identify vm-centos8
Error: cannot create any connection to the device

I followed the official guide and also I have Golang 1.16 already installed in my system.

go version go1.16.6 linux/amd64

My OS version is CentOS 8:

NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

**Comment by babos77** [comment]
`Error: cannot create any connection to the device` means that Thola is not able to create a connection to your device. Your device needs to have snmp activated for Thola to work. Per default Thola tries to reach your device over snmp v1 or v2c with `public` as community string. You can change these parameters, for example by using command line flags. For all possible flags use `thola identify -h`.

**Comment by wh1te0wl** [comment]
Hello,

Im getting error once again, I dont know what Im doing wrong.

[root@centos-8-server thola]# ./thola read disk 192.168.x.x
No result
[root@centos-8-server thola]# ./thola read cpu-load 192.168.x.x
Error: can't get cpu load: failed to get CPUComponentCPULoad: failed to read out property
[root@centos-8-server thola]# ./thola read count-interfaces 192.168.x.x
Count: 0
[root@centos-8-server thola]# ./thola read memory-usage 192.168.x.x
Error: can't get memory usage: failed to get MemoryComponentMemoryUsage: failed to read out property
[root@centos-8-server thola]# ./thola identify 192.168.x.x
Device:
  Class: linux
[root@centos-8-server thola]#


Regards,

**Comment by wh1te0wl** [comment]
> `Error: cannot create any connection to the device` means that Thola is not able to create a connection to your device. Your device needs to have snmp activated for Thola to work. Per default Thola tries to reach your device over snmp v1 or v2c with `public` as community string. You can change these parameters, for example by using command line flags. For all possible flags use `thola identify -h`.

Yes, It worked. Thanks.
Actually, thola does not obtain the custom string from the snmpd.conf file, so, we need to explicit set as a parameter:

./thola identify --snmp-community YOUR-SNMP-COMMUNITY-STRING --snmp-port 161 192.168.x.x
